# Generated by Django 5.2.12 on 2026-04-23 15:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('position_name', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract')], default='full_time', max_length=16)),
                ('weekly_capacity_hours', models.PositiveSmallIntegerField(default=40)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='operations.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('estimated_hours', models.PositiveSmallIntegerField()),
                ('actual_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='operations.department')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_plan_run_id', models.UUIDField(blank=True, null=True)),
                ('planned_hours', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='proposed', max_length=16)),
                ('assigned_by_type', models.CharField(choices=[('system', 'System'), ('manager', 'Manager'), ('admin', 'Admin')], default='system', max_length=16)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_assignments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='operations.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='operations.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_level', models.PositiveSmallIntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_requirements', to='operations.skill')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='operations.task')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='operations.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('is_working_day', models.BooleanField(default=True)),
                ('capacity_hours', models.PositiveSmallIntegerField(default=8)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='operations.workschedule')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_log', to='operations.assignment')),
                ('changed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_changes', to=settings.AUTH_USER_MODEL)),
                ('new_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_assignment_changes', to='operations.employee')),
                ('old_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_assignment_changes', to='operations.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['assignment'], name='assign_change_assignment_idx'), models.Index(fields=['created_at'], name='assign_change_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAvailabilityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available_hours', models.PositiveSmallIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_availability_overrides', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_overrides', to='operations.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['employee'], name='availability_employee_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_override_date'), models.CheckConstraint(condition=models.Q(('available_hours__lte', 24)), name='override_hours_lte_24')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacation'), ('sick_leave', 'Sick leave'), ('day_off', 'Day off'), ('business_trip', 'Business trip')], max_length=24)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='approved', max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='operations.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['employee'], name='employee_leave_employee_idx'), models.Index(fields=['employee', 'start_date', 'end_date'], name='employee_leave_period_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='leave_valid_period')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='operations.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='operations.skill')),
            ],
            options={
                'indexes': [models.Index(fields=['employee'], name='employee_skill_employee_idx'), models.Index(fields=['skill'], name='employee_skill_skill_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'skill'), name='unique_employee_skill'), models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 5)), name='employee_skill_level_1_5')],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='task_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='task_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='task_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['department'], name='task_department_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('start_date__lte', models.F('due_date')), _connector='OR'), name='task_valid_period'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['task'], name='assignment_task_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['employee'], name='assignment_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status'], name='assignment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['source_plan_run_id'], name='assignment_plan_run_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='assignment_valid_period'),
        ),
        migrations.AddIndex(
            model_name='taskrequirement',
            index=models.Index(fields=['task'], name='task_requirement_task_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrequirement',
            index=models.Index(fields=['skill'], name='task_requirement_skill_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskrequirement',
            constraint=models.UniqueConstraint(fields=('task', 'skill'), name='unique_task_requirement'),
        ),
        migrations.AddIndex(
            model_name='workscheduleday',
            index=models.Index(fields=['schedule'], name='schedule_day_schedule_idx'),
        ),
        migrations.AddConstraint(
            model_name='workscheduleday',
            constraint=models.UniqueConstraint(fields=('schedule', 'weekday'), name='unique_schedule_weekday'),
        ),
        migrations.AddConstraint(
            model_name='workscheduleday',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='schedule_weekday_0_6'),
        ),
        migrations.AddConstraint(
            model_name='workscheduleday',
            constraint=models.CheckConstraint(condition=models.Q(('capacity_hours__lte', 24)), name='schedule_capacity_lte_24'),
        ),
    ]
