# Generated by Django 5.2.13 on 2026-05-12 17:00

from django.conf import settings
from django.db import migrations, models
from django.db.models import Case, F, IntegerField, Q, Value, When


def normalize_task_actual_hours_before_constraint(apps, schema_editor):
    """Backfill legacy task rows so the new lifecycle constraint can be applied safely."""

    Task = apps.get_model('operations', 'Task')

    # Non-done tasks must not keep legacy actual_hours values.
    Task.objects.exclude(status='done').exclude(actual_hours__isnull=True).update(actual_hours=None)

    # Done tasks must keep a positive actual_hours; use estimated_hours fallback when possible.
    Task.objects.filter(status='done').filter(
        Q(actual_hours__isnull=True) | Q(actual_hours__lte=0)
    ).update(
        actual_hours=Case(
            When(estimated_hours__gt=0, then=F('estimated_hours')),
            default=Value(1),
            output_field=IntegerField(),
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            normalize_task_actual_hours_before_constraint,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actual_hours__gt', 0), ('status', 'done')), models.Q(models.Q(('status', 'done'), _negated=True), ('actual_hours__isnull', True)), _connector='OR'), name='task_actual_hours_match_done_status'),
        ),
    ]
