# Generated by Django 5.2.13 on 2026-05-12 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actual_hours__gt', 0), ('status', 'done')), models.Q(models.Q(('status', 'done'), _negated=True), ('actual_hours__isnull', True)), _connector='OR'), name='task_actual_hours_match_done_status'),
        ),
    ]
